pub const APP_NAME: &str = "np-setup";
pub const APP_DESCRIPTION: &str = "NetProbe Setup Tool";
pub const APP_VERSION: &str = "0.1.0";
pub const APP_NETPROBE_GUI_URL: &str = "https://github.com/shellrow/netprobe";
pub const APP_NETPROBE_CLI_URL: &str = "https://github.com/shellrow/netprobe-cli";
pub const NPCAP_SOFTWARE_NAME: &str = "Npcap";
pub const NPCAP_INSTALLER_FILENAME: &str = "npcap-1.76.exe";
pub const NPCAP_INSTALLER_HASH: &str = "3C846F5F62A217E3CF2052749CDE159E946248022781097C58815386DA6B9C46";
pub const NPCAP_DIST_BASE_URL: &str = "https://npcap.com/dist/";
